/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: state.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "state.pb-c.h"
void   state__code_pos__init
                     (State__CodePos         *message)
{
  static const State__CodePos init_value = STATE__CODE_POS__INIT;
  *message = init_value;
}
size_t state__code_pos__get_packed_size
                     (const State__CodePos *message)
{
  assert(message->base.descriptor == &state__code_pos__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t state__code_pos__pack
                     (const State__CodePos *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &state__code_pos__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t state__code_pos__pack_to_buffer
                     (const State__CodePos *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &state__code_pos__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
State__CodePos *
       state__code_pos__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (State__CodePos *)
     protobuf_c_message_unpack (&state__code_pos__descriptor,
                                allocator, len, data);
}
void   state__code_pos__free_unpacked
                     (State__CodePos *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &state__code_pos__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   state__array8__init
                     (State__Array8         *message)
{
  static const State__Array8 init_value = STATE__ARRAY8__INIT;
  *message = init_value;
}
size_t state__array8__get_packed_size
                     (const State__Array8 *message)
{
  assert(message->base.descriptor == &state__array8__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t state__array8__pack
                     (const State__Array8 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &state__array8__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t state__array8__pack_to_buffer
                     (const State__Array8 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &state__array8__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
State__Array8 *
       state__array8__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (State__Array8 *)
     protobuf_c_message_unpack (&state__array8__descriptor,
                                allocator, len, data);
}
void   state__array8__free_unpacked
                     (State__Array8 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &state__array8__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   state__array32__init
                     (State__Array32         *message)
{
  static const State__Array32 init_value = STATE__ARRAY32__INIT;
  *message = init_value;
}
size_t state__array32__get_packed_size
                     (const State__Array32 *message)
{
  assert(message->base.descriptor == &state__array32__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t state__array32__pack
                     (const State__Array32 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &state__array32__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t state__array32__pack_to_buffer
                     (const State__Array32 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &state__array32__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
State__Array32 *
       state__array32__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (State__Array32 *)
     protobuf_c_message_unpack (&state__array32__descriptor,
                                allocator, len, data);
}
void   state__array32__free_unpacked
                     (State__Array32 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &state__array32__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   state__array64__init
                     (State__Array64         *message)
{
  static const State__Array64 init_value = STATE__ARRAY64__INIT;
  *message = init_value;
}
size_t state__array64__get_packed_size
                     (const State__Array64 *message)
{
  assert(message->base.descriptor == &state__array64__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t state__array64__pack
                     (const State__Array64 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &state__array64__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t state__array64__pack_to_buffer
                     (const State__Array64 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &state__array64__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
State__Array64 *
       state__array64__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (State__Array64 *)
     protobuf_c_message_unpack (&state__array64__descriptor,
                                allocator, len, data);
}
void   state__array64__free_unpacked
                     (State__Array64 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &state__array64__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   state__typed_array__init
                     (State__TypedArray         *message)
{
  static const State__TypedArray init_value = STATE__TYPED_ARRAY__INIT;
  *message = init_value;
}
size_t state__typed_array__get_packed_size
                     (const State__TypedArray *message)
{
  assert(message->base.descriptor == &state__typed_array__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t state__typed_array__pack
                     (const State__TypedArray *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &state__typed_array__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t state__typed_array__pack_to_buffer
                     (const State__TypedArray *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &state__typed_array__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
State__TypedArray *
       state__typed_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (State__TypedArray *)
     protobuf_c_message_unpack (&state__typed_array__descriptor,
                                allocator, len, data);
}
void   state__typed_array__free_unpacked
                     (State__TypedArray *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &state__typed_array__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   state__label_stack__init
                     (State__LabelStack         *message)
{
  static const State__LabelStack init_value = STATE__LABEL_STACK__INIT;
  *message = init_value;
}
size_t state__label_stack__get_packed_size
                     (const State__LabelStack *message)
{
  assert(message->base.descriptor == &state__label_stack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t state__label_stack__pack
                     (const State__LabelStack *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &state__label_stack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t state__label_stack__pack_to_buffer
                     (const State__LabelStack *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &state__label_stack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
State__LabelStack *
       state__label_stack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (State__LabelStack *)
     protobuf_c_message_unpack (&state__label_stack__descriptor,
                                allocator, len, data);
}
void   state__label_stack__free_unpacked
                     (State__LabelStack *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &state__label_stack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   state__call_stack_entry__init
                     (State__CallStackEntry         *message)
{
  static const State__CallStackEntry init_value = STATE__CALL_STACK_ENTRY__INIT;
  *message = init_value;
}
size_t state__call_stack_entry__get_packed_size
                     (const State__CallStackEntry *message)
{
  assert(message->base.descriptor == &state__call_stack_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t state__call_stack_entry__pack
                     (const State__CallStackEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &state__call_stack_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t state__call_stack_entry__pack_to_buffer
                     (const State__CallStackEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &state__call_stack_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
State__CallStackEntry *
       state__call_stack_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (State__CallStackEntry *)
     protobuf_c_message_unpack (&state__call_stack_entry__descriptor,
                                allocator, len, data);
}
void   state__call_stack_entry__free_unpacked
                     (State__CallStackEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &state__call_stack_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   state__call_stack__init
                     (State__CallStack         *message)
{
  static const State__CallStack init_value = STATE__CALL_STACK__INIT;
  *message = init_value;
}
size_t state__call_stack__get_packed_size
                     (const State__CallStack *message)
{
  assert(message->base.descriptor == &state__call_stack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t state__call_stack__pack
                     (const State__CallStack *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &state__call_stack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t state__call_stack__pack_to_buffer
                     (const State__CallStack *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &state__call_stack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
State__CallStack *
       state__call_stack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (State__CallStack *)
     protobuf_c_message_unpack (&state__call_stack__descriptor,
                                allocator, len, data);
}
void   state__call_stack__free_unpacked
                     (State__CallStack *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &state__call_stack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor state__code_pos__field_descriptors[2] =
{
  {
    "fidx",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(State__CodePos, fidx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(State__CodePos, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned state__code_pos__field_indices_by_name[] = {
  0,   /* field[0] = fidx */
  1,   /* field[1] = offset */
};
static const ProtobufCIntRange state__code_pos__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor state__code_pos__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "state.CodePos",
  "CodePos",
  "State__CodePos",
  "state",
  sizeof(State__CodePos),
  2,
  state__code_pos__field_descriptors,
  state__code_pos__field_indices_by_name,
  1,  state__code_pos__number_ranges,
  (ProtobufCMessageInit) state__code_pos__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor state__array8__field_descriptors[1] =
{
  {
    "contents",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(State__Array8, contents),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned state__array8__field_indices_by_name[] = {
  0,   /* field[0] = contents */
};
static const ProtobufCIntRange state__array8__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor state__array8__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "state.Array8",
  "Array8",
  "State__Array8",
  "state",
  sizeof(State__Array8),
  1,
  state__array8__field_descriptors,
  state__array8__field_indices_by_name,
  1,  state__array8__number_ranges,
  (ProtobufCMessageInit) state__array8__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor state__array32__field_descriptors[1] =
{
  {
    "contents",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(State__Array32, n_contents),
    offsetof(State__Array32, contents),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned state__array32__field_indices_by_name[] = {
  0,   /* field[0] = contents */
};
static const ProtobufCIntRange state__array32__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor state__array32__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "state.Array32",
  "Array32",
  "State__Array32",
  "state",
  sizeof(State__Array32),
  1,
  state__array32__field_descriptors,
  state__array32__field_indices_by_name,
  1,  state__array32__number_ranges,
  (ProtobufCMessageInit) state__array32__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor state__array64__field_descriptors[1] =
{
  {
    "contents",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(State__Array64, n_contents),
    offsetof(State__Array64, contents),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned state__array64__field_indices_by_name[] = {
  0,   /* field[0] = contents */
};
static const ProtobufCIntRange state__array64__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor state__array64__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "state.Array64",
  "Array64",
  "State__Array64",
  "state",
  sizeof(State__Array64),
  1,
  state__array64__field_descriptors,
  state__array64__field_indices_by_name,
  1,  state__array64__number_ranges,
  (ProtobufCMessageInit) state__array64__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor state__typed_array__field_descriptors[2] =
{
  {
    "types",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(State__TypedArray, types),
    &state__array8__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(State__TypedArray, values),
    &state__array32__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned state__typed_array__field_indices_by_name[] = {
  0,   /* field[0] = types */
  1,   /* field[1] = values */
};
static const ProtobufCIntRange state__typed_array__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor state__typed_array__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "state.TypedArray",
  "TypedArray",
  "State__TypedArray",
  "state",
  sizeof(State__TypedArray),
  2,
  state__typed_array__field_descriptors,
  state__typed_array__field_indices_by_name,
  1,  state__typed_array__number_ranges,
  (ProtobufCMessageInit) state__typed_array__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor state__label_stack__field_descriptors[4] =
{
  {
    "begins",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(State__LabelStack, n_begins),
    offsetof(State__LabelStack, begins),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "targets",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(State__LabelStack, n_targets),
    offsetof(State__LabelStack, targets),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stack_pointers",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(State__LabelStack, n_stack_pointers),
    offsetof(State__LabelStack, stack_pointers),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cell_nums",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(State__LabelStack, n_cell_nums),
    offsetof(State__LabelStack, cell_nums),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned state__label_stack__field_indices_by_name[] = {
  0,   /* field[0] = begins */
  3,   /* field[3] = cell_nums */
  2,   /* field[2] = stack_pointers */
  1,   /* field[1] = targets */
};
static const ProtobufCIntRange state__label_stack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor state__label_stack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "state.LabelStack",
  "LabelStack",
  "State__LabelStack",
  "state",
  sizeof(State__LabelStack),
  4,
  state__label_stack__field_descriptors,
  state__label_stack__field_indices_by_name,
  1,  state__label_stack__number_ranges,
  (ProtobufCMessageInit) state__label_stack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor state__call_stack_entry__field_descriptors[4] =
{
  {
    "pc",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(State__CallStackEntry, pc),
    &state__code_pos__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "locals",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(State__CallStackEntry, locals),
    &state__typed_array__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_stack",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(State__CallStackEntry, value_stack),
    &state__typed_array__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "label_stack",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(State__CallStackEntry, label_stack),
    &state__label_stack__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned state__call_stack_entry__field_indices_by_name[] = {
  3,   /* field[3] = label_stack */
  1,   /* field[1] = locals */
  0,   /* field[0] = pc */
  2,   /* field[2] = value_stack */
};
static const ProtobufCIntRange state__call_stack_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor state__call_stack_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "state.CallStackEntry",
  "CallStackEntry",
  "State__CallStackEntry",
  "state",
  sizeof(State__CallStackEntry),
  4,
  state__call_stack_entry__field_descriptors,
  state__call_stack_entry__field_indices_by_name,
  1,  state__call_stack_entry__number_ranges,
  (ProtobufCMessageInit) state__call_stack_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor state__call_stack__field_descriptors[1] =
{
  {
    "entries",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(State__CallStack, n_entries),
    offsetof(State__CallStack, entries),
    &state__call_stack_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned state__call_stack__field_indices_by_name[] = {
  0,   /* field[0] = entries */
};
static const ProtobufCIntRange state__call_stack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor state__call_stack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "state.CallStack",
  "CallStack",
  "State__CallStack",
  "state",
  sizeof(State__CallStack),
  1,
  state__call_stack__field_descriptors,
  state__call_stack__field_indices_by_name,
  1,  state__call_stack__number_ranges,
  (ProtobufCMessageInit) state__call_stack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
